#!/bin/sh
export PATH=/usr/local/bin:$PATH

ktlint_recommended_version="0.40.0"

ktlint_remote_version="$(curl -s -X GET ec2-18-130-42-20.eu-west-2.compute.amazonaws.com/version/ktlint 2> /dev/null)"
ktlint_version="${ktlint_remote_version:=$ktlint_recommended_version}"

if [ ${#ktlint_version} -ge 10 ]; then ktlint_version="$ktlint_recommended_version"; fi

ktlint_error="Aborting commit...\nPlease install the latest version of ktlint by running the setup script in the utilities folder."

empty_regex='no message'
empty_error="Aborting commit due to empty commit message."

conflict_regex='(conflict|conflicts|Conflicts|Conflict)'
conflict_error="Aborting commit...\nYour commit message is referencing conflicts of a merge. Please remove it!"

installed=$(ktlint -V 2> /dev/null)

if [ "$installed" != "$ktlint_version" ]; then 
	echo "$ktlint_error" >&2
	exit 1
fi

if grep -iqE "$empty_regex" "$1" ; then
    echo "$empty_error" >&2
    exit 1
else
	if grep -iqE "$conflict_regex" "$1"; then
	    echo "$conflict_error" >&2
	    exit 1
	fi
fi
