#!/bin/sh
export PATH=/usr/local/bin:$PATH

ktlint_recommended_version="0.40.0"

ktlint_remote_version="$(curl -s -X GET ec2-18-130-42-20.eu-west-2.compute.amazonaws.com/version/ktlint 2> /dev/null)"
ktlint_version="${ktlint_remote_version:=$ktlint_recommended_version}"

if [ ${#ktlint_version} -ge 10 ]; then ktlint_version="$ktlint_recommended_version"; fi

ktlint_error="Aborting commit...\nPlease install the latest version of ktlint by running the setup script in the utilities folder."

installed=$(ktlint -V 2> /dev/null)

if [ "$installed" != "$ktlint_version" ]; then 
	echo "$ktlint_error" >&2
	exit 1
fi

git diff --name-only HEAD origin/$(git rev-parse --abbrev-ref HEAD) | grep '\.kt[s"]\?$' | xargs ktlint --relative .
if [ $? -ne 0 ]; then exit 1; fi